### PR TITLE
select genes with high variance

### PR DESCRIPTION
**Pull request by imyiningliu**

### CODE REVIEW

**Comment by jeff-regier** [comment]
Does this always select 600 genes? Do we want that to be something the user sets?

**Comment by jeff-regier** [comment]
Ok time to move on. :-)

**Comment by imyiningliu** [comment]
Romain used 600 in the paper. I can make it a parameter if that's what we want.

**Comment by jeff-regier** [comment]
Usually better make hard carded values parameters, perhaps with default values. But it's not so important. For now, more important finish wrapping brain small, pbmc, and hemato.

**Pull request merged**
