### PR TITLE
select genes with high variance 

### PR DESCRIPTION
**Pull request by imyiningliu**
Sorry, I forgot to only include the 600 genes with high variance for cbmc dataset. Just fixed that.

### CODE REVIEW

**Comment by jeff-regier** [comment]
Looks like you need to rebase on master first. Otherwise all the old commits are part of the pull request.

**Comment by jeff-regier** [comment]
See https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by imyiningliu** [comment]
I wasn't able to rebase because of a merge conflict in the test file. Is that okay if I start a new branch and submit pull request from that branch?

**Comment by jeff-regier** [comment]
Sure, that's fine

**Pull request closed without merging**
